backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: "https://abhizworld.netlify.app"
display_url: "https://abhizworld.netlify.app"

logo_url: "/assets/images/logo.png"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - {
          label: "Date",
          name: "date",
          widget: "datetime"
        }

      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false
        }

      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false
        }

      - {
          label: "Body",
          name: "body",
          widget: "markdown"
        }
